from flask import Flask, request, jsonify, send_from_directory
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import json
import re
from datetime import datetime

app = Flask(__name__)

# Initialize Groq with your actual API key
groq_api_key = "your_api_key"  # Replace with your actual Groq API key

# Create the chat model
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.3-70b-versatile",  # Updated model name
)

# User data storage (in production, use a database)
user_data = {
    'skill_level': 'beginner',
    'experience_points': 0,
    'completed_lessons': [],
    'streak_days': 1,
    'last_active': datetime.now().strftime('%Y-%m-%d')
}

def is_programming_related(query):
    """Check if the user's query is related to programming."""
    programming_keywords = [
        "code", "program", "debug", "error", "python", "javascript", "java", "algorithm",
        "function", "loop", "API", "database", "web", "app", "html", "css", "react", "node",
        "flask", "django", "git", "github", "bug", "fix", "compile", "syntax", "variable",
        "class", "object", "framework", "library", "package", "pip", "npm", "yarn", "docker",
        "kubernetes", "server", "client", "frontend", "backend", "devops", "cloud", "aws",
        "azure", "gcp", "linux", "windows", "mac", "terminal", "command", "script", "shell",
        "bash", "zsh", "ssh", "http", "https", "api", "json", "xml", "sql","py","compare","code", "program", "debug", "error", "python", "javascript", "java", "algorithm",
        "function", "loop", "API", "database", "web", "app", "html", "css", "react", "node",
        "flask", "django", "git", "github", "bug", "fix", "compile", "syntax", "variable",
        "class", "object", "framework", "library", "package", "pip", "npm", "yarn", "docker",
        "kubernetes", "server", "client", "frontend", "backend", "devops", "cloud", "aws",
        "azure", "gcp", "linux", "windows", "mac", "terminal", "command", "script", "shell",
        "bash", "zsh", "ssh", "http", "https", "api", "json", "xml", "sql","code", "program", "debug", "error", "python", "javascript", "java", "algorithm",
        "function", "loop", "API", "database", "web", "app", "html", "css", "react", "node",
        "flask", "django", "git", "github", "bug", "fix", "compile", "syntax", "variable",
        "class", "object", "framework", "library", "package", "pip", "npm", "yarn", "docker",
        "kubernetes", "server", "client", "frontend", "backend", "devops", "cloud", "aws",
        "azure", "gcp", "linux", "windows", "mac", "terminal", "command", "script", "shell",
        "bash", "zsh", "ssh", "http", "https", "api", "json", "xml", "sql", "nosql", "mongodb",
        "mysql", "postgresql", "redis", "graphql", "rest", "soap", "websocket", "socket",
        "tcp", "udp", "ip", "dns", "ssl", "tls", "security", "authentication", "authorization",
        "oauth", "jwt", "cookie", "session", "cache", "load balancer", "microservice",
        "monolith", "agile", "scrum", "kanban", "ci/cd", "jenkins", "travis", "circleci",
        "github actions", "gitlab", "bitbucket", "vscode", "pycharm", "intellij", "eclipse",
        "sublime", "atom", "vim", "emacs", "docker", "kubernetes", "terraform", "ansible",
        "puppet", "chef", "vagrant", "virtualbox", "vmware", "hyper-v", "aws", "azure",
        "gcp", "digitalocean", "linode", "heroku", "netlify", "vercel", "firebase",
        "lambda", "serverless", "graphql", "grpc", "protobuf", "thrift", "avro", "parquet",
        "csv", "excel", "spreadsheet", "data", "analysis", "visualization", "tableau",
        "powerbi", "matplotlib", "seaborn", "pandas", "numpy", "scipy", "scikit-learn",
        "tensorflow", "pytorch", "keras", "opencv", "nlp", "machine learning", "deep learning",
        "ai", "artificial intelligence", "neural network", "reinforcement learning",
        "supervised learning", "unsupervised learning", "clustering", "classification",
        "regression", "decision tree", "random forest", "svm", "knn", "k-means", "pca",
        "svd", "lda", "qda", "naive bayes", "gradient boosting", "xgboost", "lightgbm",
        "catboost", "hadoop", "spark", "kafka", "flink", "storm", "beam", "dataflow",
        "bigquery", "redshift", "snowflake", "databricks", "hive", "pig", "hbase", "cassandra",
        "couchbase", "riak", "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph",
        "arangodb", "redis", "memcached", "elasticsearch", "solr", "splunk", "logstash",
        "kibana", "grafana", "prometheus", "zabbix", "nagios", "new relic", "datadog",
        "splunk", "sumologic", "appdynamics", "dynatrace", "cloudwatch", "stackdriver",
        "azure monitor", "sentry", "rollbar", "bugsnag", "airbrake", "raygun", "honeybadger",
        "loggly", "papertrail", "logentries", "logz.io", "loki", "fluentd", "fluentbit",
        "vector", "filebeat", "metricbeat", "packetbeat", "heartbeat", "auditbeat",
        "journalbeat", "winlogbeat", "functionbeat", "apm", "rum", "synthetics", "profiling",
        "tracing", "metrics", "logs", "events", "alerts", "incidents", "notifications",
        "slack", "microsoft teams", "pagerduty", "opsgenie", "victorops", "xmatters",
        "webhooks", "email", "sms", "phone", "push", "in-app", "chat", "voice", "video",
        "screen sharing", "remote desktop", "vnc", "rdp", "ssh", "sftp", "scp", "rsync",
        "ftp", "ftps", "sftp", "http", "https", "websocket", "grpc", "rest", "graphql",
        "soap", "xml", "json", "yaml", "toml", "ini", "env", "csv", "tsv", "xlsx", "ods",
        "pdf", "doc", "docx", "ppt", "pptx", "txt", "md", "html", "css", "js", "ts", "jsx",
        "tsx", "vue", "svelte", "angular", "react", "next", "nuxt", "gatsby", "gridsome",
        "quasar", "bootstrap", "tailwind", "foundation", "bulma", "materialize", "semantic ui",
        "ant design", "chakra ui", "styled components", "emotion", "sass", "less", "stylus",
        "postcss", "purgecss", "css modules", "css-in-js", "webpack", "rollup", "parcel",
        "vite", "snowpack", "esbuild", "swc", "babel", "typescript", "flow", "eslint",
        "prettier", "stylelint", "husky", "lint-staged", "commitlint", "commitizen",
        "standard version", "semantic release", "conventional commits", "git hooks",
        "gitflow", "github flow", "gitlab flow", "trunk based development", "feature flags",
        "feature toggles", "canary releases", "blue-green deployment", "rolling deployment",
        "recreate deployment", "shadow deployment", "dark launch", "ab testing", "multivariate testing",
        "split testing", "bucket testing", "smoke testing", "sanity testing", "regression testing",
        "integration testing", "unit testing", "end-to-end testing", "ui testing", "api testing",
        "load testing", "stress testing", "soak testing", "spike testing", "performance testing",
        "security testing", "penetration testing", "vulnerability scanning", "threat modeling",
        "risk assessment", "incident response", "disaster recovery", "business continuity",
        "high availability", "fault tolerance", "scalability", "elasticity", "resilience",
        "redundancy", "replication", "sharding", "partitioning", "indexing", "caching",
        "load balancing", "auto-scaling", "monitoring", "alerting", "logging", "tracing",
        "metrics", "observability", "telemetry", "distributed tracing", "opentelemetry",
        "jaeger", "zipkin", "prometheus", "grafana", "loki", "tempo", "cortex", "thanos",
        "victoriametrics", "influxdb", "timescaledb", "questdb", "druid", "pinot", "kudu",
        "kylin", "doris", "clickhouse", "presto", "trino", "athena", "bigquery", "redshift",
        "snowflake", "databricks", "hive", "pig", "hbase", "cassandra", "couchbase", "riak",
        "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph", "redis", "memcached",
        "elasticsearch", "solr", "splunk", "logstash", "kibana", "grafana", "prometheus",
        "zabbix", "nagios", "new relic", "datadog", "splunk", "sumologic", "appdynamics",
        "dynatrace", "cloudwatch", "stackdriver", "azure monitor", "sentry", "rollbar",
        "bugsnag", "airbrake", "raygun", "honeybadger", "loggly", "papertrail", "logentries",
        "logz.io", "loki", "fluentd", "fluentbit", "vector", "filebeat", "metricbeat",
        "packetbeat", "heartbeat", "auditbeat", "journalbeat", "winlogbeat", "functionbeat",
        "apm", "rum", "synthetics", "profiling", "tracing", "metrics", "logs", "events",
        "alerts", "incidents", "notifications", "slack", "microsoft teams", "pagerduty",
        "opsgenie", "victorops", "xmatters", "webhooks", "email", "sms", "phone", "push",
        "in-app", "chat", "voice", "video", "screen sharing", "remote desktop", "vnc",
        "rdp", "ssh", "sftp", "scp", "rsync", "ftp", "ftps", "sftp", "http", "https",
        "websocket", "grpc", "rest", "graphql", "soap", "xml", "json", "yaml", "toml",
        "ini", "env", "csv", "tsv", "xlsx", "ods", "pdf", "doc", "docx", "ppt", "pptx",
        "txt", "md", "html", "css", "js", "ts", "jsx", "tsx", "vue", "svelte", "angular",
        "react", "next", "nuxt", "gatsby", "gridsome", "quasar", "bootstrap", "tailwind",
        "foundation", "bulma", "materialize", "semantic ui", "ant design", "chakra ui",
        "styled components", "emotion", "sass", "less", "stylus", "postcss", "purgecss",
        "css modules", "css-in-js", "webpack", "rollup", "parcel", "vite", "snowpack",
        "esbuild", "swc", "babel", "typescript", "flow", "eslint", "prettier", "stylelint",
        "husky", "lint-staged", "commitlint", "commitizen", "standard version", "semantic release",
        "conventional commits", "git hooks", "gitflow", "github flow", "gitlab flow",
        "trunk based development", "feature flags", "feature toggles", "canary releases",
        "blue-green deployment", "rolling deployment", "recreate deployment", "shadow deployment",
        "dark launch", "ab testing", "multivariate testing", "split testing", "bucket testing",
        "smoke testing", "sanity testing", "regression testing", "integration testing",
        "unit testing", "end-to-end testing", "ui testing", "api testing", "load testing",
        "stress testing", "soak testing", "spike testing", "performance testing", "security testing",
        "penetration testing", "vulnerability scanning", "threat modeling", "risk assessment",
        "incident response", "disaster recovery", "business continuity", "high availability",
        "fault tolerance", "scalability", "elasticity", "resilience", "redundancy", "replication",
        "sharding", "partitioning", "indexing", "caching", "load balancing", "auto-scaling",
        "monitoring", "alerting", "logging", "tracing", "metrics", "observability", "telemetry",
        "distributed tracing", "opentelemetry", "jaeger", "zipkin", "prometheus", "grafana",
        "loki", "tempo", "cortex", "thanos", "victoriametrics", "influxdb", "timescaledb",
        "questdb", "druid", "pinot", "kudu", "kylin", "doris", "clickhouse", "presto",
        "trino", "athena", "bigquery", "redshift", "snowflake", "databricks", "hive",
        "pig", "hbase", "cassandra", "couchbase", "riak", "neo4j", "arangodb", "orientdb",
        "titan", "janusgraph", "dgraph", "redis", "memcached", "elasticsearch", "solr",
        "splunk", "logstash", "kibana", "grafana", "prometheus", "zabbix", "nagios",
        "new relic", "datadog", "splunk", "sumologic", "appdynamics", "dynatrace", "cloudwatch",
        "stackdriver", "azure monitor", "sentry", "rollbar", "bugsnag", "airbrake", "raygun",
        "honeybadger", "loggly", "papertrail", "logentries", "logz.io", "loki", "fluentd",
        "fluentbit", "vector", "filebeat", "metricbeat", "packetbeat", "heartbeat", "auditbeat",
        "journalbeat", "winlogbeat", "functionbeat", "apm", "rum", "synthetics", "profiling",
        "tracing", "metrics", "logs", "events", "alerts", "incidents", "notifications",
        "slack", "microsoft teams", "pagerduty", "opsgenie", "victorops", "xmatters",
        "webhooks", "email", "sms", "phone", "push", "in-app", "chat", "voice", "video",
        "screen sharing", "remote desktop", "vnc", "rdp", "ssh", "sftp", "scp", "rsync",
        "ftp", "ftps", "sftp", "http", "https", "websocket", "grpc", "rest", "graphql",
        "soap", "xml", "json", "yaml", "toml", "ini", "env", "csv", "tsv", "xlsx", "ods",
        "pdf", "doc", "docx", "ppt", "pptx", "txt", "md", "html", "css", "js", "ts", "jsx",
        "tsx", "vue", "svelte", "angular", "react", "next", "nuxt", "gatsby", "gridsome",
        "quasar", "bootstrap", "tailwind", "foundation", "bulma", "materialize", "semantic ui",
        "ant design", "chakra ui", "styled components", "emotion", "sass", "less", "stylus",
        "postcss", "purgecss", "css modules", "css-in-js", "webpack", "rollup", "parcel",
        "vite", "snowpack", "esbuild", "swc", "babel", "typescript", "flow", "eslint",
        "prettier", "stylelint", "husky", "lint-staged", "commitlint", "commitizen",
        "standard version", "semantic release", "conventional commits", "git hooks",
        "gitflow", "github flow", "gitlab flow", "trunk based development", "feature flags",
        "feature toggles", "canary releases", "blue-green deployment", "rolling deployment",
        "recreate deployment", "shadow deployment", "dark launch", "ab testing", "multivariate testing",
        "split testing", "bucket testing", "smoke testing", "sanity testing", "regression testing",
        "integration testing", "unit testing", "end-to-end testing", "ui testing", "api testing",
        "load testing", "stress testing", "soak testing", "spike testing", "performance testing",
        "security testing", "penetration testing", "vulnerability scanning", "threat modeling",
        "risk assessment", "incident response", "disaster recovery", "business continuity",
        "high availability", "fault tolerance", "scalability", "elasticity", "resilience",
        "redundancy", "replication", "sharding", "partitioning", "indexing", "caching",
        "load balancing", "auto-scaling", "monitoring", "alerting", "logging", "tracing",
        "metrics", "observability", "telemetry", "distributed tracing", "opentelemetry",
        "jaeger", "zipkin", "prometheus", "grafana", "loki", "tempo", "cortex", "thanos",
        "victoriametrics", "influxdb", "timescaledb", "questdb", "druid", "pinot", "kudu",
        "kylin", "doris", "clickhouse", "presto", "trino", "athena", "bigquery", "redshift",
        "snowflake", "databricks", "hive", "pig", "hbase", "cassandra", "couchbase", "riak",
        "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph", "redis", "memcached",
        "elasticsearch", "solr", "splunk", "logstash", "kibana", "grafana", "prometheus",
        "zabbix", "nagios", "new relic", "datadog", "splunk", "sumologic", "appdynamics",
        "dynatrace", "cloudwatch", "stackdriver", "azure monitor", "sentry", "rollbar",
        "bugsnag", "airbrake", "raygun", "honeybadger", "loggly", "papertrail", "logentries",
        "logz.io", "loki", "fluentd", "fluentbit", "vector", "filebeat", "metricbeat",
        "packetbeat", "heartbeat", "auditbeat", "journalbeat", "winlogbeat", "functionbeat",
        "apm", "rum", "synthetics", "profiling", "tracing", "metrics", "logs", "events",
        "alerts", "incidents", "notifications", "slack", "microsoft teams", "pagerduty",
        "opsgenie", "victorops", "xmatters", "webhooks", "email", "sms", "phone", "push",
        "in-app", "chat", "voice", "video", "screen sharing", "remote desktop", "vnc",
        "rdp", "ssh", "sftp", "scp", "rsync", "ftp", "ftps", "sftp", "http", "https",
        "websocket", "grpc", "rest", "graphql", "soap", "xml", "json", "yaml", "toml",
        "ini", "env", "csv", "tsv", "xlsx", "ods", "pdf", "doc", "docx", "ppt", "pptx",
        "txt", "md", "html", "css", "js", "ts", "jsx", "tsx", "vue", "svelte", "angular",
        "react", "next", "nuxt", "gatsby", "gridsome", "quasar", "bootstrap", "tailwind",
        "foundation", "bulma", "materialize", "semantic ui", "ant design", "chakra ui",
        "styled components", "emotion", "sass", "less", "stylus", "postcss", "purgecss",
        "css modules", "css-in-js", "webpack", "rollup", "parcel", "vite", "snowpack",
        "esbuild", "swc", "babel", "typescript", "flow", "eslint", "prettier", "stylelint",
        "husky", "lint-staged", "commitlint", "commitizen", "standard version", "semantic release",
        "conventional commits", "git hooks", "gitflow", "github flow", "gitlab flow",
        "trunk based development", "feature flags", "feature toggles", "canary releases",
        "blue-green deployment", "rolling deployment", "recreate deployment", "shadow deployment",
        "dark launch", "ab testing", "multivariate testing", "split testing", "bucket testing",
        "smoke testing", "sanity testing", "regression testing", "integration testing",
        "unit testing", "end-to-end testing", "ui testing", "api testing", "load testing",
        "stress testing", "soak testing", "spike testing", "performance testing", "security testing",
        "penetration testing", "vulnerability scanning", "threat modeling", "risk assessment",
        "incident response", "disaster recovery", "business continuity", "high availability",
        "fault tolerance", "scalability", "elasticity", "resilience", "redundancy", "replication",
        "sharding", "partitioning", "indexing", "caching", "load balancing", "auto-scaling",
        "monitoring", "alerting", "logging", "tracing", "metrics", "observability", "telemetry",
        "distributed tracing", "opentelemetry", "jaeger", "zipkin", "prometheus", "grafana",
        "loki", "tempo", "cortex", "thanos", "victoriametrics", "influxdb", "timescaledb",
        "questdb", "druid", "pinot", "kudu", "kylin", "doris", "clickhouse", "presto",
        "trino", "athena", "bigquery", "redshift", "snowflake", "databricks", "hive",
        "pig", "hbase", "cassandra", "couchbase", "riak", "neo4j", "arangodb", "orientdb",
        "titan", "janusgraph", "dgraph", "redis", "memcached", "elasticsearch", "solr",
        "splunk", "logstash", "kibana", "grafana", "prometheus", "zabbix", "nagios",
        "new relic", "datadog", "splunk", "sumologic", "appdynamics", "dynatrace", "cloudwatch",
        "stackdriver", "azure monitor", "sentry", "rollbar", "bugsnag", "airbrake", "raygun",
        "honeybadger", "loggly", "papertrail", "logentries", "logz.io", "loki", "fluentd",
        "fluentbit", "vector", "filebeat", "metricbeat", "packetbeat", "heartbeat", "auditbeat",
        "journalbeat", "winlogbeat", "functionbeat", "apm", "rum", "synthetics", "profiling",
        "tracing", "metrics", "logs", "events", "alerts", "incidents", "notifications",
        "slack", "microsoft teams", "pagerduty", "opsgenie", "victorops", "xmatters",
        "webhooks", "email", "sms", "phone", "push", "in-app", "chat", "voice", "video",
        "screen sharing", "remote desktop", "vnc", "rdp", "ssh", "sftp", "scp", "rsync",
        "ftp", "ftps", "sftp", "http", "https", "websocket", "grpc", "rest", "graphql",
        "soap", "xml", "json", "yaml", "toml", "ini", "env", "csv", "tsv", "xlsx", "ods",
        "pdf", "doc", "docx", "ppt", "pptx", "txt", "md", "html", "css", "js", "ts", "jsx",
        "tsx", "vue", "svelte", "angular", "react", "next", "nuxt", "gatsby", "gridsome",
        "quasar", "bootstrap", "tailwind", "foundation", "bulma", "materialize", "semantic ui",
        "ant design", "chakra ui", "styled components", "emotion", "sass", "less", "stylus",
        "postcss", "purgecss", "css modules", "css-in-js", "webpack", "rollup", "parcel",
        "vite", "snowpack", "esbuild", "swc", "babel", "typescript", "flow", "eslint",
        "prettier", "stylelint", "husky", "lint-staged", "commitlint", "commitizen",
        "standard version", "semantic release", "conventional commits", "git hooks",
        "gitflow", "github flow", "gitlab flow", "trunk based development", "feature flags",
        "feature toggles", "canary releases", "blue-green deployment", "rolling deployment",
        "recreate deployment", "shadow deployment", "dark launch", "ab testing", "multivariate testing",
        "split testing", "bucket testing", "smoke testing", "sanity testing", "regression testing",
        "integration testing", "unit testing", "end-to-end testing", "ui testing", "api testing",
        "load testing", "stress testing", "soak testing", "spike testing", "performance testing",
        "security testing", "penetration testing", "vulnerability scanning", "threat modeling",
        "risk assessment", "incident response", "disaster recovery", "business continuity",
        "high availability", "fault tolerance", "scalability", "elasticity", "resilience",
        "redundancy", "replication", "sharding", "partitioning", "indexing", "caching",
        "load balancing", "auto-scaling", "monitoring", "alerting", "logging", "tracing",
        "metrics", "observability", "telemetry", "distributed tracing", "opentelemetry",
        "jaeger", "zipkin", "prometheus", "grafana", "loki", "tempo", "cortex", "thanos",
        "victoriametrics", "influxdb", "timescaledb", "questdb", "druid", "pinot", "kudu",
        "kylin", "doris", "clickhouse", "presto", "trino", "athena", "bigquery", "redshift",
        "snowflake", "databricks", "hive", "pig", "hbase", "cassandra", "couchbase", "riak",
        "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph", "redis", "memcached",
        "elasticsearch", "solr", "splunk", "logstash", "kibana", "grafana", "prometheus",
        "zabbix", "nagios", "new relic", "datadog", "splunk", "sumologic", "appdynamics",
        "dynatrace", "cloudwatch", "stackdriver", "azure monitor", "sentry", "rollbar",
        "bugsnag", "airbrake", "raygun", "honeybadger", "loggly", "papertrail", "logentries",
        "logz.io", "loki", "fluentd", "fluentbit", "vector", "filebeat", "metricbeat",
        "packetbeat", "heartbeat", "auditbeat", "journalbeat", "winlogbeat", "functionbeat",
        "apm", "rum", "synthetics", "profiling", "tracing", "metrics", "logs", "events",
        "alerts", "incidents", "notifications", "slack", "microsoft teams", "pagerduty",
        "opsgenie", "victorops", "xmatters", "webhooks", "email", "sms", "phone", "push",
        "in-app", "chat", "voice", "video", "screen sharing", "remote desktop", "vnc",
        "rdp", "ssh", "sftp", "scp", "rsync", "ftp", "ftps", "sftp", "http", "https",
        "websocket", "grpc", "rest", "graphql", "soap", "xml", "json", "yaml", "toml",
        "ini", "env", "csv", "tsv", "xlsx", "ods", "pdf", "doc", "docx", "ppt", "pptx",
        "txt", "md", "html", "css", "js", "ts", "jsx", "tsx", "vue", "svelte", "angular",
        "react", "next", "nuxt", "gatsby", "gridsome", "quasar", "bootstrap", "tailwind",
        "foundation", "bulma", "materialize", "semantic ui", "ant design", "chakra ui",
        "styled components", "emotion", "sass", "less", "stylus", "postcss", "purgecss",
        "css modules", "css-in-js", "webpack", "rollup", "parcel", "vite", "snowpack",
        "esbuild", "swc", "babel", "typescript", "flow", "eslint", "prettier", "stylelint",
        "husky", "lint-staged", "commitlint", "commitizen", "standard version", "semantic release",
        "conventional commits", "git hooks", "gitflow", "github flow", "gitlab flow",
        "trunk based development", "feature flags", "feature toggles", "canary releases",
        "blue-green deployment", "rolling deployment", "recreate deployment", "shadow deployment",
        "dark launch", "ab testing", "multivariate testing", "split testing", "bucket testing",
        "smoke testing", "sanity testing", "regression testing", "integration testing",
        "unit testing", "end-to-end testing", "ui testing", "api testing", "load testing",
        "stress testing", "soak testing", "spike testing", "performance testing", "security testing",
        "penetration testing", "vulnerability scanning", "threat modeling", "risk assessment",
        "incident response", "disaster recovery", "business continuity", "high availability",
        "fault tolerance", "scalability", "elasticity", "resilience", "redundancy", "replication",
        "sharding", "partitioning", "indexing", "caching", "load balancing", "auto-scaling",
        "monitoring", "alerting", "logging", "tracing", "metrics", "observability", "telemetry",
        "distributed tracing", "opentelemetry", "jaeger", "zipkin", "prometheus", "grafana",
        "loki", "tempo", "cortex", "thanos", "victoriametrics", "influxdb", "timescaledb",
        "questdb", "druid", "pinot", "kudu", "kylin", "doris", "clickhouse", "presto",
        "trino", "athena", "bigquery", "redshift", "snowflake", "databricks", "hive",
        "pig", "hbase", "cassandra", "couchbase", "riak", "neo4j", "arangodb", "orientdb",
        "titan", "janusgraph", "dgraph", "redis", "memcached", "elasticsearch", "solr",
        "splunk", "logstash", "kibana", "grafana", "prometheus", "zabbix", "nagios",
        "new relic", "datadog", "splunk", "sumologic", "appdynamics", "dynatrace", "cloudwatch",
        "stackdriver", "azure monitor", "sentry", "rollbar", "bugsnag", "airbrake", "raygun",
        "honeybadger", "loggly", "papertrail", "logentries", "logz.io", "loki", "fluentd",
        "fluentbit", "vector", "filebeat", "metricbeat", "packetbeat", "heartbeat", "auditbeat",
        "journalbeat", "winlogbeat", "functionbeat", "apm", "rum", "synthetics", "profiling",
        "tracing", "metrics", "logs", "events", "alerts", "incidents", "notifications",
        "slack", "microsoft teams", "pagerduty", "opsgenie", "victorops", "xmatters",
        "webhooks", "email", "sms", "phone", "push", "in-app", "chat", "voice", "video",
        "screen sharing", "remote desktop", "vnc", "rdp", "ssh", "sftp", "scp", "rsync",
        "ftp", "ftps", "sftp", "http", "https", "websocket", "grpc", "rest", "graphql",
        "soap", "xml", "json", "yaml", "toml", "ini", "env", "csv", "tsv", "xlsx", "ods",
        "pdf", "doc", "docx", "ppt", "pptx", "txt", "md", "html", "css", "js", "ts", "jsx",
        "tsx", "vue", "svelte", "angular", "react", "next", "nuxt", "gatsby", "gridsome",
        "quasar", "bootstrap", "tailwind", "foundation", "bulma", "materialize", "semantic ui",
        "ant design", "chakra ui", "styled components", "emotion", "sass", "less", "stylus",
        "postcss", "purgecss", "css modules", "css-in-js", "webpack", "rollup", "parcel",
        "vite", "snowpack", "esbuild", "swc", "babel", "typescript", "flow", "eslint",
        "prettier", "stylelint", "husky", "lint-staged", "commitlint", "commitizen",
        "standard version", "semantic release", "conventional commits", "git hooks",
        "gitflow", "github flow", "gitlab flow", "trunk based development", "feature flags",
        "feature toggles", "canary releases", "blue-green deployment", "rolling deployment",
        "recreate deployment", "shadow deployment", "dark launch", "ab testing", "multivariate testing",
        "split testing", "bucket testing", "smoke testing", "sanity testing", "regression testing",
        "integration testing", "unit testing", "end-to-end testing", "ui testing", "api testing",
        "load testing", "stress testing", "soak testing", "spike testing", "performance testing",
        "security testing", "penetration testing", "vulnerability scanning", "threat modeling",
        "risk assessment", "incident response", "disaster recovery", "business continuity",
        "high availability", "fault tolerance", "scalability", "elasticity", "resilience",
        "redundancy", "replication", "sharding", "partitioning", "indexing", "caching",
        "load balancing", "auto-scaling", "monitoring", "alerting", "logging", "tracing",
        "metrics", "observability", "telemetry", "distributed tracing", "opentelemetry",
        "jaeger", "zipkin", "prometheus", "grafana", "loki", "tempo", "cortex", "thanos",
        "victoriametrics", "influxdb", "timescaledb", "questdb", "druid", "pinot", "kudu",
        "kylin", "doris", "clickhouse", "presto", "trino", "athena", "bigquery", "redshift",
        "snowflake", "databricks", "hive", "pig", "hbase", "cassandra", "couchbase", "riak",
        "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph", "redis", "memcached",
        "elasticsearch", "solr", "splunk", "logstash", "kibana", "grafana", "prometheus",
        "zabbix", "nagios", "new relic", "datadog", "splunk", "sumologic", "appdynamics",
        "dynatrace", "cloudwatch", "stackdriver", "azure monitor", "sentry", "rollbar",
        "bugsnag", "airbrake", "raygun", "honeybadger", "loggly", "papertrail", "logentries",
        "logz.io", "loki", "fluentd", "fluentbit", "vector", "filebeat", "metricbeat",
        "packetbeat", "heartbeat", "auditbeat", "journalbeat", "winlogbeat", "functionbeat",
        "apm", "rum", "synthetics", "profiling", "tracing", "metrics", "logs", "events",
        "alerts", "incidents", "notifications", "slack", "microsoft teams", "pagerduty",
        "opsgenie", "victorops", "xmatters", "webhooks", "email", "sms", "phone", "push",
        "in-app", "chat", "voice", "video", "screen sharing", "remote desktop", "vnc",
        "rdp", "ssh", "sftp", "scp", "rsync", "ftp", "ftps", "sftp", "http", "https",
        "websocket", "grpc", "rest", "graphql", "soap", "xml", "json", "yaml", "toml",
        "ini", "env", "csv", "tsv", "xlsx", "ods", "pdf", "doc", "docx", "ppt", "pptx",
        "txt", "md", "html", "css", "js", "ts", "jsx", "tsx", "vue", "svelte", "angular",
        "react", "next", "nuxt", "gatsby", "gridsome", "quasar", "bootstrap", "tailwind",
        "foundation", "bulma", "materialize", "semantic ui", "ant design", "chakra ui",
        "styled components", "emotion", "sass", "less", "stylus", "postcss", "purgecss",
        "css modules", "css-in-js", "webpack", "rollup", "parcel", "vite", "snowpack",
        "esbuild", "swc", "babel", "typescript", "flow", "eslint", "prettier", "stylelint",
        "husky", "lint-staged", "commitlint", "commitizen", "standard version", "semantic release",
        "conventional commits", "git hooks", "gitflow", "github flow", "gitlab flow",
        "trunk based development", "feature flags", "feature toggles", "canary releases",
        "blue-green deployment", "rolling deployment", "recreate deployment", "shadow deployment",
        "dark launch", "ab testing", "multivariate testing", "split testing", "bucket testing",
        "smoke testing", "sanity testing", "regression testing", "integration testing",
        "unit testing", "end-to-end testing", "ui testing", "api testing", "load testing",
        "stress testing", "soak testing", "spike testing", "performance testing", "security testing",
        "penetration testing", "vulnerability scanning", "threat modeling", "risk assessment",
        "incident response", "disaster recovery", "business continuity", "high availability",
        "fault tolerance", "scalability", "elasticity", "resilience", "redundancy", "replication",
        "sharding", "partitioning", "indexing", "caching", "load balancing", "auto-scaling",
        "monitoring", "alerting", "logging", "tracing", "metrics", "observability", "telemetry",
        "distributed tracing", "opentelemetry", "jaeger", "zipkin", "prometheus", "grafana",
        "loki", "tempo", "cortex", "thanos", "victoriametrics", "influxdb", "timescaledb",
        "questdb", "druid", "pinot", "kudu", "kylin", "doris", "clickhouse", "presto",
        "trino", "athena", "bigquery", "redshift", "snowflake", "databricks", "hive",
        "pig", "hbase", "cassandra", "couchbase", "riak", "neo4j", "arangodb", "orientdb",
        "titan", "janusgraph", "dgraph", "redis", "memcached", "elasticsearch", "solr",
        "splunk", "logstash", "kibana", "grafana", "prometheus", "zabbix", "nagios",
        "new relic", "datadog", "splunk", "sumologic", "appdynamics", "dynatrace", "cloudwatch",
        "stackdriver", "azure monitor", "sentry", "rollbar", "bugsnag", "airbrake", "raygun",
        "honeybadger", "loggly", "papertrail", "logentries", "logz.io", "loki", "fluentd",
        "fluentbit", "vector", "filebeat", "metricbeat", "packetbeat", "heartbeat", "auditbeat",
        "journalbeat", "winlogbeat", "functionbeat", "apm", "rum", "synthetics", "profiling",
        "tracing", "metrics", "logs", "events", "alerts", "incidents", "notifications",
        "slack", "microsoft teams", "pagerduty", "opsgenie", "victorops", "xmatters",
        "webhooks", "email", "sms", "phone", "push", "in-app", "chat", "voice", "video",
        "screen sharing", "remote desktop", "vnc", "rdp", "ssh", "sftp", "scp", "rsync",
        "ftp", "ftps", "sftp", "http", "https", "websocket", "grpc", "rest", "graphql",
        "soap", "xml", "json", "yaml", "toml", "ini", "env", "csv", "tsv", "xlsx", "ods",
        "pdf", "doc", "docx", "ppt", "pptx", "txt", "md", "html", "css", "js", "ts", "jsx",
        "tsx", "vue", "svelte", "angular", "react", "next", "nuxt", "gatsby", "gridsome",
        "quasar", "bootstrap", "tailwind", "foundation", "bulma", "materialize", "semantic ui",
        "ant design", "chakra ui", "styled components", "emotion", "sass", "less", "stylus",
        "postcss", "purgecss", "css modules", "css-in-js", "webpack", "rollup", "parcel",
        "vite", "snowpack", "esbuild", "swc", "babel", "typescript", "flow", "eslint",
        "prettier", "stylelint", "husky", "lint-staged", "commitlint", "commitizen",
        "standard version", "semantic release", "conventional commits", "git hooks",
        "gitflow", "github flow", "gitlab flow", "trunk based development", "feature flags",
        "feature toggles", "canary releases", "blue-green deployment", "rolling deployment",
        "recreate deployment", "shadow deployment", "dark launch", "ab testing", "multivariate testing",
        "split testing", "bucket testing", "smoke testing", "sanity testing", "regression testing",
        "integration testing", "unit testing", "end-to-end testing", "ui testing", "api testing",
        "load testing", "stress testing", "soak testing", "spike testing", "performance testing",
        "security testing", "penetration testing", "vulnerability scanning", "threat modeling",
        "risk assessment", "incident response", "disaster recovery", "business continuity",
        "high availability", "fault tolerance", "scalability", "elasticity", "resilience",
        "redundancy", "replication", "sharding", "partitioning", "indexing", "caching",
        "load balancing", "auto-scaling", "monitoring", "alerting", "logging", "tracing",
        "metrics", "observability", "telemetry", "distributed tracing", "opentelemetry",
        "jaeger", "zipkin", "prometheus", "grafana", "loki", "tempo", "cortex", "thanos",
        "victoriametrics", "influxdb", "timescaledb", "questdb", "druid", "pinot", "kudu",
        "kylin", "doris", "clickhouse", "presto", "trino", "athena", "bigquery", "redshift",
        "snowflake", "databricks", "hive", "pig", "hbase", "cassandra", "couchbase", "riak",
        "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph", "redis", "memcached",
        "elasticsearch", "solr", "splunk", "logstash", "kibana", "grafana", "prometheus",
        "zabbix", "nagios", "new relic", "datadog", "splunk", "sumologic", "appdynamics",
        "dynatrace", "cloudwatch", "stackdriver", "azure monitor", "sentry", "rollbar",
        "bugsnag", "airbrake", "raygun", "honeybadger", "loggly", "papertrail", "logentries",
        "logz.io", "loki", "fluentd", "fluentbit", "vector", "filebeat", "metricbeat",
        "packetbeat", "heartbeat", "auditbeat", "journalbeat", "winlogbeat", "functionbeat",
        "apm", "rum", "synthetics", "profiling", "tracing", "metrics", "logs", "events",
        "alerts", "incidents", "notifications", "slack", "microsoft teams", "pagerduty",
        "opsgenie", "victorops", "xmatters", "webhooks", "email", "sms", "phone", "push",
        "in-app", "chat", "voice", "video", "screen sharing", "remote desktop", "vnc",
        "rdp", "ssh", "sftp", "scp", "rsync", "ftp", "ftps", "sftp", "http", "https",
        "websocket", "grpc", "rest", "graphql", "soap", "xml", "json", "yaml", "toml",
        "ini", "env", "csv", "tsv", "xlsx", "ods", "pdf", "doc", "docx", "ppt", "pptx",
        "txt", "md", "html", "css", "js", "ts", "jsx", "tsx", "vue", "svelte", "angular",
        "react", "next", "nuxt", "gatsby", "gridsome", "quasar", "bootstrap", "tailwind",
        "foundation", "bulma", "materialize", "semantic ui", "ant design", "chakra ui",
        "styled components", "emotion", "sass", "less", "stylus", "postcss", "purgecss",
        "css modules", "css-in-js", "webpack", "rollup", "parcel", "vite", "snowpack",
        "esbuild", "swc", "babel", "typescript", "flow", "eslint", "prettier", "stylelint",
        "husky", "lint-staged", "commitlint", "commitizen", "standard version", "semantic release",
        "conventional commits", "git hooks", "gitflow", "github flow", "gitlab flow",
        "trunk based development", "feature flags", "feature toggles", "canary releases",
        "blue-green deployment", "rolling deployment", "recreate deployment", "shadow deployment",
        "dark launch", "ab testing", "multivariate testing", "split testing", "bucket testing",
        "smoke testing", "sanity testing", "regression testing", "integration testing",
        "unit testing", "end-to-end testing", "ui testing", "api testing", "load testing",
        "stress testing", "soak testing", "spike testing", "performance testing", "security testing",
        "penetration testing", "vulnerability scanning", "threat modeling", "risk assessment",
        "incident response", "disaster recovery", "business continuity", "high availability",
        "fault tolerance", "scalability", "elasticity", "resilience", "redundancy", "replication",
        "sharding", "partitioning", "indexing", "caching", "load balancing", "auto-scaling",
        "monitoring", "alerting", "logging", "tracing", "metrics", "observability", "telemetry",
        "distributed tracing", "opentelemetry", "jaeger", "zipkin", "prometheus", "grafana",
        "loki", "tempo", "cortex", "thanos", "victoriametrics", "influxdb", "timescaledb",
        "questdb", "druid", "pinot", "kudu", "kylin", "doris", "clickhouse", "presto",
        "trino", "athena", "bigquery", "redshift", "snowflake", "databricks", "hive",
        "pig", "hbase", "cassandra", "couchbase", "riak", "neo4j", "arangodb", "orientdb",
        "titan", "janusgraph", "dgraph", "redis", "memcached", "elasticsearch", "solr",
        "splunk", "logstash", "kibana", "grafana", "prometheus", "zabbix", "nagios",
        "new relic", "datadog", "splunk", "sumologic", "appdynamics", "dynatrace", "cloudwatch",
        "stackdriver", "azure monitor", "sentry", "rollbar", "bugsnag", "airbrake", "raygun",
        "honeybadger", "loggly", "papertrail", "logentries", "logz.io", "loki", "fluentd",
        "fluentbit", "vector", "filebeat", "metricbeat", "packetbeat", "heartbeat", "auditbeat",
        "journalbeat", "winlogbeat", "functionbeat", "apm", "rum", "synthetics", "profiling",
        "tracing", "metrics", "logs", "events", "alerts", "incidents", "notifications",
        "slack", "microsoft teams", "pagerduty", "opsgenie", "victorops", "xmatters",
        "webhooks", "email", "sms", "phone", "push", "in-app", "chat", "voice", "video",
        "screen sharing", "remote desktop", "vnc", "rdp", "ssh", "sftp", "scp", "rsync",
        "ftp", "ftps", "sftp", "http", "https", "websocket", "grpc", "rest", "graphql",
        "soap", "xml", "json", "yaml", "toml", "ini", "env", "csv", "tsv", "xlsx", "ods",
        "pdf", "doc", "docx", "ppt", "pptx", "txt", "md", "html", "css", "js", "ts", "jsx",
        "tsx", "vue", "svelte", "angular", "react", "next", "nuxt", "gatsby", "gridsome",
        "quasar", "bootstrap", "tailwind", "foundation", "bulma", "materialize", "semantic ui",
        "ant design", "chakra ui", "styled components", "emotion", "sass", "less", "stylus",
        "postcss", "purgecss", "css modules", "css-in-js", "webpack", "rollup", "parcel",
        "vite", "snowpack", "esbuild", "swc", "babel", "typescript", "flow", "eslint",
        "prettier", "stylelint", "husky", "lint-staged", "commitlint", "commitizen",
        "standard version", "semantic release", "conventional commits", "git hooks",
        "gitflow", "github flow", "gitlab flow", "trunk based development", "feature flags",
        "feature toggles", "canary releases", "blue-green deployment", "rolling deployment",
        "recreate deployment", "shadow deployment", "dark launch", "ab testing", "multivariate testing",
        "split testing", "bucket testing", "smoke testing", "sanity testing", "regression testing",
        "integration testing", "unit testing", "end-to-end testing", "ui testing", "api testing",
        "load testing", "stress testing", "soak testing", "spike testing", "performance testing",
        "security testing", "penetration testing", "vulnerability scanning", "threat modeling",
        "risk assessment", "incident response", "disaster recovery", "business continuity",
        "high availability", "fault tolerance", "scalability", "elasticity", "resilience",
        "redundancy", "replication", "sharding", "partitioning", "indexing", "caching",
        "load balancing", "auto-scaling", "monitoring", "alerting", "logging", "tracing",
        "metrics", "observability", "telemetry", "distributed tracing", "opentelemetry",
        "jaeger", "zipkin", "prometheus", "grafana", "loki", "tempo", "cortex", "thanos",
        "victoriametrics", "influxdb", "timescaledb", "questdb", "druid", "pinot", "kudu",
        "kylin", "doris", "clickhouse", "presto", "trino", "athena", "bigquery", "redshift",
        "snowflake", "databricks", "hive", "pig", "hbase", "cassandra", "couchbase", "riak",
        "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph", "redis", "memcached",
        "elasticsearch", "solr", "splunk", "logstash", "kibana", "grafana", "prometheus",
        "zabbix", "nagios", "new relic", "datadog", "splunk", "sumologic", "appdynamics",
        "dynatrace", "cloudwatch", "stackdriver", "azure monitor", "sentry", "rollbar",
        "bugsnag", "airbrake", "raygun", "honeybadger", "loggly", "papertrail", "logentries",
        "logz.io", "loki", "fluentd", "fluentbit", "vector", "filebeat", "metricbeat",
        "packetbeat", "heartbeat", "auditbeat", "journalbeat", "winlogbeat", "functionbeat",
        "apm", "rum", "synthetics", "profiling", "tracing", "metrics", "logs", "events",
        "alerts", "incidents", "notifications", "slack", "microsoft teams", "pagerduty",
        "opsgenie", "victorops", "xmatters", "webhooks", "email", "sms", "phone", "push",
        "in-app", "chat", "voice", "video", "screen sharing", "remote desktop", "vnc",
        "rdp", "ssh", "sftp", "scp", "rsync", "ftp", "ftps", "sftp", "http", "https",
        "websocket", "grpc", "rest", "graphql", "soap", "xml", "json", "yaml", "toml",
        "ini", "env", "csv", "tsv", "xlsx", "ods", "pdf", "doc", "docx", "ppt", "pptx",
        "txt", "md", "html", "css", "js", "ts", "jsx", "tsx", "vue", "svelte", "angular",
        "react", "next", "nuxt", "gatsby", "gridsome", "quasar", "bootstrap", "tailwind",
        "foundation", "bulma", "materialize", "semantic ui", "ant design", "chakra ui",
        "styled components", "emotion", "sass", "less", "stylus", "postcss", "purgecss",
        "css modules", "css-in-js", "webpack", "rollup", "parcel", "vite", "snowpack",
        "esbuild", "swc", "babel", "typescript", "flow", "eslint", "prettier", "stylelint",
        "husky", "lint-staged", "commitlint", "commitizen", "standard version", "semantic release",
        "conventional commits", "git hooks", "gitflow", "github flow", "gitlab flow",
        "trunk based development", "feature flags", "feature toggles", "canary releases",
        "blue-green deployment", "rolling deployment", "recreate deployment", "shadow deployment",
        "dark launch", "ab testing", "multivariate testing", "split testing", "bucket testing",
        "smoke testing", "sanity testing", "regression testing", "integration testing",
        "unit testing", "end-to-end testing", "ui testing", "api testing", "load testing",
        "stress testing", "soak testing", "spike testing", "performance testing", "security testing",
        "penetration testing", "vulnerability scanning", "threat modeling", "risk assessment",
        "incident response", "disaster recovery", "business continuity", "high availability",
        "fault tolerance", "scalability", "elasticity", "resilience", "redundancy", "replication",
        "sharding", "partitioning", "indexing", "caching", "load balancing", "auto-scaling",
        "monitoring", "alerting", "logging", "tracing", "metrics", "observability", "telemetry",
        "distributed tracing", "opentelemetry", "jaeger", "zipkin", "prometheus", "grafana",
        "loki", "tempo", "cortex", "thanos", "victoriametrics", "influxdb", "timescaledb",
        "questdb", "druid", "pinot", "kudu", "kylin", "doris", "clickhouse", "presto",
        "trino", "athena", "bigquery", "redshift", "snowflake", "databricks", "hive",
        "pig", "hbase", "cassandra", "couchbase", "riak", "neo4j", "arangodb", "orientdb",
        "titan", "janusgraph", "dgraph", "redis", "memcached", "elasticsearch", "solr",
        "splunk", "logstash", "kibana", "grafana", "prometheus", "zabbix", "nagios",
        "new relic", "datadog", "splunk", "sumologic", "appdynamics", "dynatrace", "cloudwatch",
        "stackdriver", "azure monitor", "sentry", "rollbar", "bugsnag", "airbrake", "raygun",
        "honeybadger", "loggly", "papertrail", "logentries", "logz.io", "loki", "fluentd",
        "fluentbit", "vector", "filebeat", "metricbeat", "packetbeat", "heartbeat", "auditbeat",
        "journalbeat", "winlogbeat", "functionbeat", "apm", "rum", "synthetics", "profiling",
        "tracing", "metrics", "logs", "events", "alerts", "incidents", "notifications",
        "slack", "microsoft teams", "pagerduty", "opsgenie", "victorops", "xmatters",
        "webhooks", "email", "sms", "phone", "push", "in-app", "chat", "voice", "video",
        "screen sharing", "remote desktop", "vnc", "rdp", "ssh", "sftp", "scp", "rsync",
        "ftp", "ftps", "sftp", "http", "https", "websocket", "grpc", "rest", "graphql",
        "soap", "xml", "json", "yaml", "toml", "ini", "env", "csv", "tsv", "xlsx", "ods",
        "pdf", "doc", "docx", "ppt", "pptx", "txt", "md", "html", "css", "js", "ts", "jsx",
        "tsx", "vue", "svelte", "angular", "react", "next", "nuxt", "gatsby", "gridsome",
        "quasar", "bootstrap", "tailwind", "foundation", "bulma", "materialize", "semantic ui",
        "ant design", "chakra ui", "styled components", "emotion", "sass", "less", "stylus",
        "postcss", "purgecss", "css modules", "css-in-js", "webpack", "rollup", "parcel",
        "vite", "snowpack", "esbuild", "swc", "babel", "typescript", "flow", "eslint",
        "prettier", "stylelint", "husky", "lint-staged", "commitlint", "commitizen",
        "standard version", "semantic release", "conventional commits", "git hooks",
        "gitflow", "github flow", "gitlab flow", "trunk based development", "feature flags",
        "feature toggles", "canary releases", "blue-green deployment", "rolling deployment",
        "recreate deployment", "shadow deployment", "dark launch", "ab testing", "multivariate testing",
        "split testing", "bucket testing", "smoke testing", "sanity testing", "regression testing",
        "integration testing", "unit testing", "end-to-end testing", "ui testing", "api testing",
        "load testing", "stress testing", "soak testing", "spike testing", "performance testing",
        "security testing", "penetration testing", "vulnerability scanning", "threat modeling",
        "risk assessment", "incident response", "disaster recovery", "business continuity",
        "high availability", "fault tolerance", "scalability", "elasticity", "resilience",
        "redundancy", "replication", "sharding", "partitioning", "indexing", "caching",
        "load balancing", "auto-scaling", "monitoring", "alerting", "logging", "tracing",
        "metrics", "observability", "telemetry", "distributed tracing", "opentelemetry",
        "jaeger", "zipkin", "prometheus", "grafana", "loki", "tempo", "cortex", "thanos",
        "victoriametrics", "influxdb", "timescaledb", "questdb", "druid", "pinot", "kudu",
        "kylin", "doris", "clickhouse", "presto", "trino", "athena", "bigquery", "redshift",
        "snowflake", "databricks", "hive", "pig", "hbase", "cassandra", "couchbase", "riak",
        "neo4j", "arangodb", "orientdb", "titan", "janusgraph", "dgraph", "redis", "memcached",
        "elasticsearch", "solr", "splunk", "logstash", "kibana", "grafana", "prometheus",
        "zabbix", "nagios", "new relic", "datadog", "splunk", "sumologic", "appdynamics",
        "dynatrace", "cloudwatch", "stackdriver", "azure monitor", "sentry", "rollbar",
        "bugsnag", "airbrake", "raygun", "honeybadger", "loggly", "papertrail", "logentries",
        "logz.io", "loki", "fluentd", "fluentbit", "vector", "filebeat", "metricbeat",
        "packetbeat", "heartbeat", "auditbeat", "journalbeat", "winlogbeat", "functionbeat",
        "apm", "rum", "synthetics", "profiling", "tracing", "metrics", "logs", "events",
        "alerts", "incidents", "notifications", "slack", "microsoft teams", "pagerduty",
        "opsgenie", "victorops", "xmatters", "webhooks", "email", "sms", "phone", "push",
        "in-app", "chat", "voice", "video", "screen sharing", "remote desktop", "vnc",
        "rdp", "ssh", "sftp", "scp", "rsync", "ftp", "ftps", "sftp", "http", "https",
        "websocket", "grpc", "rest", "graphql", "soap", "xml", "json", "yaml", "toml",
        "ini", "env", "csv", "tsv", "xlsx", "ods", "pdf", "doc", "docx", "ppt", "pptx",
        "txt", "md", "html", "css", "js", "ts", "jsx", "tsx", "vue", "svelte", "angular",
        "react", "next", "nuxt", "gatsby", "gridsome", "quasar", "bootstrap", "tailwind",
        "foundation", "bulma", "materialize", "semantic ui", "ant design", "chakra ui",
        "styled components", "emotion", "sass", "less", "stylus", "postcss", "purgecss",
        "css modules", "css-in-js", "webpack", "rollup", "parcel", "vite", "snowpack",
        "esbuild", "swc", "babel", "typescript", "flow", "eslint", "prettier", "stylelint",
        "husky", "lint-staged", "commitlint", "commitizen", "standard version", "semantic release",
        "conventional commits", "git hooks", "gitflow", "github flow", "gitlab flow",
        "trunk based development", "feature flags", "feature toggles", "canary releases",
        "blue-green deployment", "rolling deployment", "recreate deployment", "shadow deployment",
        "dark launch", "ab testing", "multivariate testing", "split testing", "bucket testing",
        "smoke testing", "sanity testing", "regression testing", "integration testing",
        "unit testing", "end-to-end testing", "ui testing", "api testing", "load testing",
        "stress testing", "soak testing", "spike testing", "performance testing", "security testing",
        "penetration testing", "vulnerability scanning", "threat modeling", "risk assessment",
        "incident response", "disaster recovery", "business continuity", "high availability",
        "fault tolerance", "scalability", "elasticity", "resilience", "redundancy", "replication",
        "sharding", "partitioning", "indexing", "caching", "load balancing", "auto-scaling",
        "monitoring", "alerting", "logging", "tracing", "metrics", "observability", "telemetry",
        "distributed tracing", "opentelemetry", "jaeger", "zipkin", "prometheus", "grafana",
        "loki", "tempo", "cortex", "thanos", "victoriametrics", "influxdb", "timescaledb",
        "questdb", "druid", "pinot", "kudu", "kylin", "doris", "clickhouse", "presto",
        "trino", "athena", "bigquery", "redshift", "snowflake", "databricks", "hive",
        "pig", "hbase", "cassandra", "couchbase", "riak", "neo4j", "arangodb", "orientdb",
        "titan", "janusgraph", "dgraph", "redis", "memcached", "elasticsearch", "solr",
        "splunk", "logstash", "kibana", "grafana", "prometheus", "zabbix", "nagios",
        "new relic","hi","hello","good","morning"
    ]
    return any(keyword in query.lower() for keyword in programming_keywords)

def format_response(response_content, mode):
    if mode == 'eli5':
        # Simplify the response for ELI5 mode
        response_content = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', response_content)
        response_content = re.sub(r'\*(.*?)\*', r'<em>\1</em>', response_content)
        response_content = re.sub(r'### (.*)', r'<h3>🎈 \1</h3>', response_content)
        response_content = re.sub(r'## (.*)', r'<h2>🌟 \1</h2>', response_content)
        response_content = re.sub(r'# (.*)', r'<h1>🚀 \1</h1>', response_content)
        response_content = re.sub(r'- (.*)', r'<li>👉 \1</li>', response_content)
        response_content = response_content.replace('\n', '<br>')
        response_content = response_content.replace('code', '🖥️ code')
        response_content = response_content.replace('learn', '📚 learn')
        response_content = response_content.replace('fun', '🎉 fun')
        response_content = response_content.replace('Python', '🐍 Python')
    else:
        response_content = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', response_content)
        response_content = re.sub(r'\*(.*?)\*', r'<em>\1</em>', response_content)
        response_content = re.sub(r'### (.*)', r'<h3>\1</h3>', response_content)
        response_content = re.sub(r'## (.*)', r'<h2>\1</h2>', response_content)
        response_content = re.sub(r'# (.*)', r'<h1>\1</h1>', response_content)
        response_content = re.sub(r'- (.*)', r'<li>\1</li>', response_content)
        response_content = response_content.replace('\n', '<br>')
    return response_content

@app.route('/')
def home():
    return send_from_directory('static', 'index.html')

@app.route('/static/<path:path>')
def serve_static(path):
    return send_from_directory('static', path)

@app.route('/chat', methods=['POST'])
def chat():
    try:
        data = request.json
        if not data or 'message' not in data:
            return jsonify({"response": "Invalid request. Please provide a 'message' field."})

        user_message = data['message']
        mode = data.get('mode', 'normal')

        if not user_message.strip():
            return jsonify({"response": "Please enter a valid message."})

        if not is_programming_related(user_message):
            return jsonify({
                "response": "I'm here to help with programming and coding questions! If you have any coding problems or need help with debugging, feel free to ask."
            })

        # Update system prompt based on mode
        system_message = {
            'normal': "You are a professional programming mentor. Only respond to programming-related questions.",
            'eli5': "You are explaining programming concepts in the simplest terms possible, as if explaining to a 5-year-old. Only respond to programming-related questions.",
            'debug': "You are a debugging expert. Only respond to programming-related questions.",
            'expert': "You are an advanced programming mentor. Only respond to programming-related questions."
        }.get(mode, "You are a helpful programming mentor. Only respond to programming-related questions.")

        # Prepare the messages for the Groq API
        messages = [
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message}
        ]

        # Generate response using Groq API
        response = llm.invoke(messages)

        # Extract the content from the AIMessage object
        response_content = response.content if hasattr(response, 'content') else str(response)

        # Format the response
        formatted_response = format_response(response_content, mode)

        # Update user progress
        user_data['experience_points'] += 10

        return jsonify({
            "response": formatted_response,
            "stats": user_data
        })

    except Exception as e:
        print(f"Error: {str(e)}")
        return jsonify({"response": f"An error occurred: {str(e)}. Please try again."})

if __name__ == '__main__':
    app.run(debug=True, port=5000)